version: '2'
volumes:
  redis_data:
networks:
  redis:
services:
  app:
    image: python:3.6
    depends_on:
      - redis
    networks:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
    networks:
      - redis
